version: "3"

services:
  gateway.default.svc.cluster.local:
    build: ./gateway-service
    restart: on-failure
    ports:
      - 443:443
      - 80:80
    volumes:
      - /mnt/gateway/certs:/certs
      - ./ingress.yaml:/root/ingress.yaml
    depends_on:
      - redis.default.svc.cluster.local

  led-strip.default.svc.cluster.local:
    build: ./led-strip-service
    restart: on-failure
    depends_on:
      - redis.default.svc.cluster.local

  hue.default.svc.cluster.local:
    build: ./hue-service
    restart: on-failure
    depends_on:
      - redis.default.svc.cluster.local

  food.default.svc.cluster.local:
    build: ./food-service
    restart: on-failure
    depends_on:
      - redis.default.svc.cluster.local

  tapo.default.svc.cluster.local:
    build: ./tapo-service
    restart: on-failure
    depends_on:
      - redis.default.svc.cluster.local

  registry.default.svc.cluster.local:
    build: ./registry-service
    restart: on-failure
    depends_on:
      - redis.default.svc.cluster.local

  web.default.svc.cluster.local:
    build: ./client/web/vue/home-automation
    restart: on-failure

  mqtt-broker.default.svc.cluster.local:
    image: eclipse-mosquitto
    restart: on-failure
    ports:
      - 1883:1883

  redis.default.svc.cluster.local:
    image: redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - /mnt/redis-data:/data
    entrypoint: redis-server --appendonly yes

volumes:
  redis_data:
    driver: local
