version: "3"

services:
  gateway.default.svc.cluster.local:
    image: rubenwo/home-automation-gateway-service:latest
    # build: ./services/gateway-service
    restart: on-failure
    environment:
      - JWT_KEY=$JWT_KEY
      - ENABLE_ADMIN=true
      - ADMIN_PWD=$ADMIN_PWD
      - PRODUCTION=true
      - DOMAINS=homeautomation.rubenwoldhuis.nl
    ports:
      - 443:443
      - 80:80
    volumes:
      - /mnt/gateway/certs:/certs
      - ./ingress.yaml:/root/ingress.yaml
    depends_on:
      - postgres.default.svc.cluster.local

  led-strip.default.svc.cluster.local:
    image: rubenwo/home-automation-led-strip-service:latest
    # build: ./services/led-strip-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  hue.default.svc.cluster.local:
    image: rubenwo/home-automation-hue-service:latest
    # build: ./services/hue-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  food.default.svc.cluster.local:
    image: rubenwo/home-automation-food-service:latest
    # build: ./services/food-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  tapo.default.svc.cluster.local:
    image: rubenwo/home-automation-tapo-service:latest
    # build: ./services/tapo-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  registry.default.svc.cluster.local:
    image: rubenwo/home-automation-registry-service:latest
    # build: ./services/registry-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  notification.default.svc.cluster.local:
    image: rubenwo/home-automation-notification-service:latest
    # build: ./services/notification-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local
      - mqtt-broker.default.svc.cluster.local
    volumes:
      - ./service-account-file.json:/root/service-account-file.json

  inventory.default.svc.cluster.local:
    image: rubenwo/home-automation-inventory-service:latest
    # build: ./services/inventory-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  qr.default.svc.cluster.local:
    image: rubenwo/home-automation-qr-service:latest
    # build: ./services/qr-service
    restart: on-failure

  web.default.svc.cluster.local:
    image: rubenwo/home-automation-web-client:latest
    # build: ./client/web/home-automation
    restart: on-failure

  video-streaming-hub.default.svc.cluster.local:
    image: rubenwo/home-automation-video-streaming-hub-service:latest
    # build: ./services/video-streaming-hub-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  actions.default.svc.cluster.local:
    image: rubenwo/home-automation-actions-service:latest
    # build: ./services/actions-service
    restart: on-failure
    depends_on:
      - postgres.default.svc.cluster.local

  tradfri.default.svc.cluster.local:
    image: rubenwo/home-automation-tradfri-service:latest
    # build: ./services/tradfri-service
    restart: on-failure
    environment:
      - TRADFRI_GATEWAY_ADDRESS=192.168.178.52:5684
      - TRADFRI_GATEWAY_CLIENT_ID=$TRADFRI_GATEWAY_CLIENT_ID
      - TRADFRI_GATEWAY_PSK=$TRADFRI_GATEWAY_PSK
    depends_on:
      - postgres.default.svc.cluster.local

  mqtt-broker.default.svc.cluster.local:
    image: eclipse-mosquitto:1.6.13
    restart: on-failure
    ports:
      - 1883:1883

  redis.default.svc.cluster.local:
    image: redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - /mnt/redis-data:/data
    entrypoint: redis-server --appendonly yes

  postgres.default.svc.cluster.local:
    image: postgres:13.4
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=inventory_database,registry_database,food_database,camera_database
    volumes:
      - /mnt/postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
