version: "3"

services:
  gateway.default.svc.cluster.local:
    build: ./gateway-service
    restart: on-failure
    ports:
      - 443:443
      - 80:80
    volumes:
      - /mnt/gateway/certs:/certs
      - ./ingress.yaml:/root/ingress.yaml

  hue.default.svc.cluster.local:
    build: ./hue-service
    restart: on-failure

  tapo.default.svc.cluster.local:
    build: ./tapo-service
    restart: on-failure

  registry.default.svc.cluster.local:
    build: ./registry-service
    restart: on-failure

  web.default.svc.cluster.local:
    build: ./client/web/home-automation
    restart: on-failure

  mqtt-broker.default.svc.cluster.local:
    image: eclipse-mosquitto
    restart: on-failure
    ports:
      - 1883:1883
