apiVersion: v1
spec:
  - host: registry.default.svc.cluster.local
    routes:
      - path: "/new_id"
        methods:
          - GET
        protocol: http
      - path: "/devices"
        methods:
          - GET
          - POST
        protocol: http
      - path: "/devices/{id}"
        methods:
          - DELETE
        protocol: http
      - path: "/schedules"
        methods:
          - GET
          - POST
        protocol: http
      - path: "/sensors"
        methods:
          - GET
          - POST
        protocol: http
      - path: "/sensors/{id}"
        methods:
          - DELETE
        protocol: http

  - host: food.default.svc.cluster.local
    routes:
      - path: "/recipes"
        methods:
          - GET
          - POST
        protocol: http
      - path: "/recipes/{id}"
        methods:
          - GET
        protocol: http
      - path: "/recipes/{id}"
        methods:
          - DELETE
        protocol: http

  - host: led-strip.default.svc.cluster.local
    routes:
      - path: "/leds/devices"
        methods:
          - GET
        protocol: http
      - path: "/leds/devices/register"
        methods:
          - POST
        protocol: http
      - path: "/leds/devices/{id}/command"
        methods:
          - POST
        protocol: http

  - host: tapo.default.svc.cluster.local
    routes:
      - path: /tapo/wake/{device_id}
        methods:
          - GET
        protocol: http
      - path: "/tapo/devices/{device_id}"
        methods:
          - GET
          - PUT
          - DELETE
        protocol: http
      - path: "/tapo/devices/register"
        methods:
          - POST
        protocol: http
      - path: "/tapo/devices"
        methods:
          - GET
        protocol: http
      - path: "/tapo/lights/{device_id}"
        methods:
          - GET
        protocol: http

  - host: hue.default.svc.cluster.local
    routes:
      - path: "/hue/devices"
        methods:
          - GET
        protocol: http

  - host: mqtt-broker.default.svc.cluster.local
    routes:
      - path: "/esp32/toggle"
        methods:
          - POST
          - GET
        protocol: mqtt

  - host: inventory.default.svc.cluster.local
    routes:
      - path: "/inventory"
        methods:
          - POST
          - GET
        protocol: http
      - path: "/inventory/{id}"
        methods:
          - DELETE
        protocol: http
