apiVersion: v1
spec:
  - host: registry.default.svc.cluster.local
    path: "/devices"
    methods:
      - GET
    protocol: http

  - host: tapo.default.svc.cluster.local
    path: "/tapo/devices/{device_id}"
    methods:
      - GET
      - PUT
    protocol: http
  - host: tapo.default.svc.cluster.local
    path: "/tapo/devices/register"
    methods:
      - POST
    protocol: http
  - host: tapo.default.svc.cluster.local
    path: "/tapo/devices"
    methods:
      - GET
    protocol: http
  - host: tapo.default.svc.cluster.local
    path: "/tapo/lights/{device_id}/{command}"
    methods:
      - GET
    protocol: http

  - host: hue.default.svc.cluster.local
    path: "/hue/devices"
    methods:
      - GET
    protocol: http

  - host: mqtt-broker.default.svc.cluster.local
    path: "/esp32/toggle"
    methods:
      - POST
      - GET
    protocol: mqtt
