apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: led-strip-service
build:
  artifacts:
  - image: rubenwo/home-automation-led-strip-service
deploy:
  kubectl:
    manifests:
    - led-strip_deployment.yaml
