apiVersion: v1
data:
  ingress.yaml: "apiVersion: v1\r\nspec:\r\n  - host: registry.default.svc.cluster.local\r\n
    \   routes:\r\n      - path: \"/new_id\"\r\n        methods:\r\n          - GET\r\n
    \       protocol: http\r\n      - path: \"/devices\"\r\n        methods:\r\n          -
    GET\r\n          - POST\r\n        protocol: http\r\n      - path: \"/devices/{id}\"\r\n
    \       methods:\r\n          - GET\r\n          - DELETE\r\n        protocol:
    http\r\n      - path: \"/routines\"\r\n        methods:\r\n          - GET\r\n
    \         - POST\r\n        protocol: http\r\n      - path: \"/routines/{id}\"\r\n
    \       methods:\r\n          - GET\r\n          - DELETE\r\n          - PUT\r\n
    \       protocol: http\r\n      - path: \"/sensors\"\r\n        methods:\r\n          -
    GET\r\n          - POST\r\n        protocol: http\r\n      - path: \"/sensors/{id}\"\r\n
    \       methods:\r\n          - DELETE\r\n        protocol: http\r\n\r\n  - host:
    food.default.svc.cluster.local\r\n    routes:\r\n      - path: \"/recipes\"\r\n
    \       methods:\r\n          - GET\r\n          - POST\r\n        protocol: http\r\n
    \     - path: \"/recipes/{id}\"\r\n        methods:\r\n          - GET\r\n          -
    PUT\r\n          - DELETE\r\n        protocol: http\r\n\r\n  - host: led-strip.default.svc.cluster.local\r\n
    \   routes:\r\n      - path: \"/leds/devices\"\r\n        methods:\r\n          -
    GET\r\n        protocol: http\r\n      - path: \"/leds/devices/register\"\r\n
    \       methods:\r\n          - POST\r\n        protocol: http\r\n      - path:
    \"/leds/devices/{id}/command\"\r\n        methods:\r\n          - POST\r\n        protocol:
    http\r\n\r\n  - host: tapo.default.svc.cluster.local\r\n    routes:\r\n      -
    path: /tapo/wake/{device_id}\r\n        methods:\r\n          - GET\r\n        protocol:
    http\r\n      - path: \"/tapo/devices/{device_id}\"\r\n        methods:\r\n          -
    GET\r\n          - PUT\r\n          - DELETE\r\n        protocol: http\r\n      -
    path: \"/tapo/devices/register\"\r\n        methods:\r\n          - POST\r\n        protocol:
    http\r\n      - path: \"/tapo/devices\"\r\n        methods:\r\n          - GET\r\n
    \       protocol: http\r\n      - path: \"/tapo/lights/{device_id}\"\r\n        methods:\r\n
    \         - GET\r\n        protocol: http\r\n\r\n  - host: hue.default.svc.cluster.local\r\n
    \   routes:\r\n      - path: \"/hue/devices\"\r\n        methods:\r\n          -
    GET\r\n        protocol: http\r\n\r\n  - host: actions.default.svc.cluster.local\r\n
    \   routes:\r\n      - path: \"/webhook/request\"\r\n        methods:\r\n          -
    POST\r\n        protocol: http\r\n\r\n  - host: mqtt-broker.default.svc.cluster.local\r\n
    \   routes:\r\n      - path: \"/esp32/toggle\"\r\n        methods:\r\n          -
    POST\r\n          - GET\r\n        protocol: mqtt\r\n\r\n  - host: inventory.default.svc.cluster.local\r\n
    \   routes:\r\n      - path: \"/inventory\"\r\n        methods:\r\n          -
    POST\r\n          - GET\r\n        protocol: http\r\n      - path: \"/inventory/{id}\"\r\n
    \       methods:\r\n          - DELETE\r\n          - PUT\r\n        protocol:
    http\r\n\r\n  - host: video-streaming-hub.default.svc.cluster.local\r\n    routes:\r\n
    \     - path: \"/cameras\"\r\n        methods:\r\n          - POST\r\n          -
    GET\r\n        protocol: http\r\n      - path: \"/camera/{id}\"\r\n        methods:\r\n
    \         - DELETE\r\n          - GET\r\n          - PUT\r\n        protocol:
    http\r\n      - path: \"/stream/ws/{id}\"\r\n        methods:\r\n          - GET\r\n
    \       protocol: http\r\n      - path: \"/stream/http/{id}\"\r\n        methods:\r\n
    \         - GET\r\n        protocol: http\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-config
