apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: tapo-service
build:
  artifacts:
  - image: rubenwo/home-automation-tapo-service
deploy:
  kubectl:
    manifests:
    - tapo_deployment.yaml
