name: Build & Publish Docker images for ARM
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}

      - name: Docker Login
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Run Buildx (push image)
        if: success()
        run: |
          docker pull rubenwo/home-automation-actions-service:1
          docker pull rubenwo/home-automation-web-client:1
          docker pull rubenwo/home-automation-food-service:1
          docker pull rubenwo/home-automation-gateway-service:1
          docker pull rubenwo/home-automation-hue-service:1
          docker pull rubenwo/home-automation-inventory-service:1
          docker pull rubenwo/home-automation-led-strip-service:1
          docker pull rubenwo/home-automation-registry-service:1
          docker pull rubenwo/home-automation-actions-service:1
          docker pull rubenwo/home-automation-video-streaming-hub-service:1

          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-actions-service:latest --file ./actions-service/Dockerfile --output type=image,push=true ./actions-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-web-client:latest --file ./client/web/vue/home-automation/Dockerfile --output type=image,push=true ./client/web/vue/home-automation
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-food-service:latest --file ./food-service/Dockerfile --output type=image,push=true ./food-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-gateway-service:latest --file ./gateway-service/Dockerfile --output type=image,push=true ./gateway-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-hue-service:latest --file ./hue-service/Dockerfile --output type=image,push=true ./hue-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-inventory-service:latest --file ./inventory-service/Dockerfile --output type=image,push=true ./inventory-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-led-strip-service:latest --file ./led-strip-service/Dockerfile --output type=image,push=true ./led-strip-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-registry-service:latest --file ./registry-service/Dockerfile --output type=image,push=true ./registry-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-tapo-service:latest --file ./tapo-service/Dockerfile --output type=image,push=true ./tapo-service
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag rubenwo/home-automation-video-streaming-hub-service:latest --file ./video-streaming-hub-service/Dockerfile --output type=image,push=true ./video-streaming-hub-service
